# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b8865a53017d50e6147616413cb2a1284c41b11bcb061b5bc935463555911fb51dd2d198b04b25010b4d3fe51a69c27d23a822157fa4b30ecec525dbd8653d3

test:
  secret_key_base: 50c273e8f7bea66c0eac424ce8a6e6bd6587e33aa446620bb28ed2857799d3883afda69f98f405694700f15ba50d20b7eb1cd5971eab3c606182846890f86f85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
